// react-native/CourtCounter/components/Team/index.js
import React from 'react';
import {View, Text, Button, StyleSheet, Platform} from 'react-native';

function Team(props) {
  const {teamName, score, addThree, addTwo, addOne} = props;
  return (
    <View style={styles.team}>
      <Text style={styles.teamName}>{teamName}</Text>
      <Text style={styles.score}>{score}</Text>
      <View style={styles.pointBtnContainer}>
        <Button color="#FF9800" title="+3 points" onPress={addThree} />
      </View>
      <View style={styles.pointBtnContainer}>
        <Button color="#FF9800" title="+2 points" onPress={addTwo} />
      </View>
      <View style={styles.pointBtnContainer}>
        <Button color="#FF9800" title="free throw" onPress={addOne} />
      </View>
    </View>
  );
}

const styles = StyleSheet.create({
  team: {
    flex: 1,
    justifyContent: 'center',
  },
  teamName: {
    textAlign: 'center',
    fontFamily:
      Platform.OS === 'android' ? 'sans-serif-medium' : 'PingFangSC-Medium',
    fontSize: 14,
    color: '#616161',
    paddingTop: 16,
    paddingBottom: 16,
  },
  score: {
    textAlign: 'center',
    fontFamily:
      Platform.OS === 'android' ? 'sans-serif-light' : 'PingFangSC-Light',
    fontSize: 56,
    color: '#000',
    marginBottom: 24,
  },
  pointBtnContainer: {
    marginLeft: 24,
    marginRight: 24,
    marginBottom: 8,
  },
});

export default Team;

// weex/court-counter/src/components/Team.vue
<template>
  <div class="team">
    <text class="team-name">{{ teamName }}</text>
    <text class="score">{{ score }}</text>
    <div class="btn-container">
      <button class="btn" text="+3 Points" @press="onAddThree"></button>
    </div>
      <div class="btn-container">
        <button class="btn" text="+2 Points" @press="onAddTwo"></button>
      </div>
      <div class="btn-container">
        <button class="btn" text="Free Throw" @press="onAddOne"></button>
      </div>
  </div>
</template>

<script>
import Button from './Button';

export default {
  name: 'Team',
  components: {
    Button
  },
  props: {
    teamName: {
      type: String,
      required: true
    },
    score: {
      type: Number,
      required: true
    }
  },
  methods: {
    onAddThree() {
      this.$emit('addThree');
    },
    onAddTwo() {
      this.$emit('addTwo');
    },
    onAddOne() {
      this.$emit('addOne');
    }
  }
};
</script>

<style scoped>
  .team {
    flex: 1;
  }

  .team-name {
    padding-top: 32px;
    padding-bottom: 32px;
    font-family: 'sans-serif-medium';
    font-size: 14wx;
    color: #616161;
    text-align: center;
  }

  .score {
    margin-bottom: 48px;
    font-family: 'sans-serif-light';
    font-size: 56wx;
    color: #000;
    text-align: center;
  }

  .btn-container {
    margin-left: 48px;
    margin-right: 48px;
    margin-bottom: 16px;
  }

  .btn {
    background-color: #ff9800;
  }
</style>
